#server ??
server:
  error:
    include-exception: true
    include-stacktrace: always
    path: /error
    whitelabel:
      enabled: false
  port: 9000

spring:
  application:
    name: RePlatform2023
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  datasource:
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        lazyLoadingEnabled: true
      jdbc-url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3306}/re_platform?characterEncoding=UTF-8&useCursorFetch=true
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3306}/re_platform?characterEncoding=UTF-8&useCursorFetch=true
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      connection-test-query: SELECT NOW() FROM dual
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*Mapper.xml

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG




